language: ruby
dist: trusty
sudo: false

git:
  depth: 2

node_js:
  - node

rvm:
  - 2.3.1

gemfile:
  - Gemfile

cache:
  directories:
  - vendor/bundle       # bundler cache folder
  - $HOME/.cache/yarn   # yarn cache folder

env:
  global:
    secure: "VoGU9V0tAvGYElZs2XgfWk5hsMSqPwe/wWLiGs3iJQrmhIq+MKXeqEW5jrxl+1tFSu6MKF4mV0abbTxgH/tyE1/2eC5sNP5sOKLmj11T8RyZGNS4ZyftEyxLfTxWYmK1PbfNnXho7P6wV6zS3uxIr6853bR8G6fQTIyq0J46hk1ngkzdzfyTkKN4icj2aoALnUaoQOjIcJTDa92tUuVmRg4dw9JsAoixSapGkwsgOb7SS+FjJDWuYo71eE3X6T2Ij8xzfdSkfT9FQ5kFs2s4Wvl4kMgZ8bGwktp1aN7rBckLodskIjy2ixYekQabEkfvGGed1fOUHFgeoVJSsqnR2VZyQngSfxcTni6PNofrYXCf+qCKsZgIBAG9rYVKMM+Px17fDGr/3+u60SfcjjIi8LfM179P0Wz3fCferjzCA8LnC3d5+ZEL5Ip8Z9AOqApMZjCx59B4rB2YsYwKLwrKjB4/5Je8HjFXoRXkAwE0siwWCxZr5VNa57S9eWMT43cBEe2KZtPR7impnIJvv6ALW01OtMVWCsdfxWZjslNxTFfpRbC7niiZgiVw1QbNFqhF61yupWMBzet1R8Y9vQj0Ba9vE9Gvgvqf7dmipXHQMJ9ZbUBj7T+ghpV00sQGiQzjyUTr6yrhs4KyOxhr66hfqmMb2lCAGa+cAq6hWEKbhqs="


addons:
  apt:
    # Pour ajouter yarn via apt
    # sources:
    # - sourceline: 'deb http://dl.yarnpkg.com/debian/ stable main'
    #   key_url: 'http://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - imagemagick
      - graphicsmagick
      # - yarn

# https://docs.travis-ci.com/user/customizing-the-build
before_install:
  # - echo "Branch: $TRAVIS_BRANCH  |  Version: $TRAVIS_BUILD_NUMBER"
  # - rvm install 2.3.1
  # Installation de Yarn
  - rvm list
  # - curl portquiz.net:8080
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  # - rm -rf ~/.nvm
  # - nvm --version
  - nvm list

  # Installation de NVM, si besoin
  # - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  # - nvm --version
  # - nvm install $NODE_JS_VERSION

  - nvm use stable
  - node --version
  # - npm install -g gulp
  # - npm install -g casperjs
  - yarn global add gulp casperjs
  - yarn
  # install ruby dependencies
  # - gem install jekyll
  # - gem install bundler
  - bundle install --jobs=3 --retry=3
  - bundle package   # Package the .gem files required into the vendor/cache directory
  # extract the phantomjs binary in local path
  # - curl -o- -sSL https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar --strip-components=2 -xjf - phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  # - sudo ln -sf `pwd`/phantomjs /usr/local/bin/phantomjs
  - phantomjs --version
  - casperjs --version

# before_script:

script:
  - npm run travis
  - sleep 3
  - npm run test

after_script:
  - pkill -f jekyll -9
  - sleep 1

before_deploy:
  - openssl aes-256-cbc -K $encrypted_734a8a68f501_key -iv $encrypted_734a8a68f501_iv -in travis_key.enc -out ~/.ssh/travis_key -d
  - chmod +x ./scripts/deploy.sh


deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: inares/site
    branch: release


# before_deploy:
#   - export archive_file_name=site_$(date +%Y-%m-%d_%H-%M-%S).tar.bz2
#   - tar -cjf $archive_file_name _site/
#   - ls -lFh --time-style="+%d/%m/%y %H:%m" $archive_file_name
  # - git config --global user.email "builds@travis-ci.com"
  # - git config --global user.name "Travis CI"
  # - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  # - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  # - git push origin --tags

# deploy:
#   provider: releases
#   api_key:
#     secure: PSvz9BUllifr7l9eilu8auw6KXsiYFg1sDOTiWnSFJfz4pTr66VG/FbCUkQz1uxjp+isSTIBHf82BVcPbpj5QmwfVY/hIgOqlitkbojDbmjGUU7rgnqT3y5IoXXsjhXMI7Qu9CAIB4Q9JuI0q95q5zo1xyfqERHgrxuY5FOeU4/3h0bo7ZQPQsYZozzzHx7yLezKKeYNJzNUft+0wAzNNdIURVpbNcEOVrdWSr29q9yer0hW+D21WalCLnNvsAlH8bforSdN5sfEuNO4r4oAHg2kQSZIPOsMTJpqRF9Dm8CjsE7tYnrS3f9/wkLFNRLpYIFSGBvWiaIIt4D1GthJ//7xrJfLe8HrY4Pj4w7sbohmJusSQYWQzowunWxQoYEK/crUJDIEw2Wy1Gdu98pAtAAwfkMKlHy6DBQhpg90n4ulZEkLdaBzXIZhbPjX1IYdDmjLThmMuxLN5P+yE1UyJSTaXaPI0h4eIWwLWPLYl1DgjeVhvt34KzpH/nBoLSX4C4TjYn/Q+SMpGgJOl/8j7YIw6TBeVXVx3N0+5K17P1Ijb+5ZMUOP0tY28mIaSP7YX3ifqrOuOd2SGMedwRx3ZQt1a8bKzLXJqNSswlpGyPDyhFaA06G1Vy4DzSJwa0J3y/3t6Y3Vn2gfsyCIh/tlWo3NQ4jJI1ny92POGtWO+ug=
#   file: site*.tar.bz2
#   file_glob: "true"
#   skip_cleanup: true
#   on:
#     repo: inares/site
#     branch: release
#     tags: true
