language: ruby
dist: trusty
sudo: false

git:
  depth: 2

node_js:
  - node

rvm:
  - 2.3.1

gemfile:
  - Gemfile

cache:
  directories :
  - vendor/bundle       # bundler cache folder
  - $HOME/.cache/yarn   # yarn cache folder

addons:
  apt:
    # Pour ajouter yarn via apt
    # sources:
    # - sourceline: 'deb http://dl.yarnpkg.com/debian/ stable main'
    #   key_url: 'http://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
    - imagemagick
    - graphicsmagick
    # - yarn

# https://docs.travis-ci.com/user/customizing-the-build
before_install:
  - echo "Branch: $TRAVIS_BRANCH  |  Version: $TRAVIS_BUILD_NUMBER"
  # - rvm install 2.3.1
  # Installation de Yarn
  - rvm list
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  # - rm -rf ~/.nvm
  # - nvm --version
  - nvm list

  # Installation de NVM, si besoin
  # - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  # - nvm --version
  # - nvm install $NODE_JS_VERSION

  - nvm use stable
  - node --version
  # - npm install -g gulp
  # - npm install -g casperjs
  - yarn global add gulp casperjs
  - yarn
  # install ruby dependencies
  # - gem install jekyll
  # - gem install bundler
  - bundle install --jobs=3 --retry=3
  - bundle package   # Package the .gem files required into the vendor/cache directory
  # extract the phantomjs binary in local path
  # - curl -o- -sSL https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar --strip-components=2 -xjf - phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  # - sudo ln -sf `pwd`/phantomjs /usr/local/bin/phantomjs
  - phantomjs --version
  - casperjs --version

# before_script:

script:
  - npm run travis
  - sleep 1
  - npm run test

after_script:
  - pkill -f jekyll
  - sleep 1


before_deploy:
  - export archive_file_name=site_$(date +%Y-%m-%d_%H-%M-%S).tar.bz2
  - tar -cjf $archive_file_name _site/
  - ls -lFh --time-style="+%d/%m/%y %H:%m" $archive_file_name
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push origin --tags

deploy:
  provider: releases
  api_key:
    secure: PSvz9BUllifr7l9eilu8auw6KXsiYFg1sDOTiWnSFJfz4pTr66VG/FbCUkQz1uxjp+isSTIBHf82BVcPbpj5QmwfVY/hIgOqlitkbojDbmjGUU7rgnqT3y5IoXXsjhXMI7Qu9CAIB4Q9JuI0q95q5zo1xyfqERHgrxuY5FOeU4/3h0bo7ZQPQsYZozzzHx7yLezKKeYNJzNUft+0wAzNNdIURVpbNcEOVrdWSr29q9yer0hW+D21WalCLnNvsAlH8bforSdN5sfEuNO4r4oAHg2kQSZIPOsMTJpqRF9Dm8CjsE7tYnrS3f9/wkLFNRLpYIFSGBvWiaIIt4D1GthJ//7xrJfLe8HrY4Pj4w7sbohmJusSQYWQzowunWxQoYEK/crUJDIEw2Wy1Gdu98pAtAAwfkMKlHy6DBQhpg90n4ulZEkLdaBzXIZhbPjX1IYdDmjLThmMuxLN5P+yE1UyJSTaXaPI0h4eIWwLWPLYl1DgjeVhvt34KzpH/nBoLSX4C4TjYn/Q+SMpGgJOl/8j7YIw6TBeVXVx3N0+5K17P1Ijb+5ZMUOP0tY28mIaSP7YX3ifqrOuOd2SGMedwRx3ZQt1a8bKzLXJqNSswlpGyPDyhFaA06G1Vy4DzSJwa0J3y/3t6Y3Vn2gfsyCIh/tlWo3NQ4jJI1ny92POGtWO+ug=
  file: site*.tar.bz2
  file_glob: "true"
  skip_cleanup: true
  on:
    repo: inares/site
    branch: release
    tags: true
