language: ruby
dist: trusty
sudo: false

git:
  depth: 2

node_js:
  - node

rvm:
  - 2.3.1

gemfile:
  - Gemfile

env:
  - NODE_JS_VERSION=7.8.0

cache:
# - bundler: true
# - yarn: true
  directories :
  - vendor/bundle
  - $HOME/.cache/yarn

addons:
  apt:
    # sources:
    # - sourceline: 'deb http://dl.yarnpkg.com/debian/ stable main'
    #   key_url: 'http://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
    - imagemagick
    - graphicsmagick
    # - yarn

# https://docs.travis-ci.com/user/customizing-the-build
before_install:
  # - rvm install 2.4.0
  # Installation de Yarn
  - rvm list
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  # - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  # - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list > /dev/null

install:
  # - rm -rf ~/.nvm
  # - nvm --version
  - nvm list

  # Installation de NVM
  # - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  # - nvm --version
  # - nvm install $NODE_JS_VERSION

  - nvm use stable
  - node --version
  # - npm install -g gulp
  # - npm install -g casperjs
  - yarn global add gulp casperjs
  - yarn
  # install ruby dependencies
  # - gem install jekyll
  # - gem install bundler
  - bundle install --jobs=3 --retry=3
  # extract the phantomjs binary in local path
  # - curl -o- -sSL https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar --strip-components=2 -xjf - phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  # - sudo ln -sf `pwd`/phantomjs /usr/local/bin/phantomjs
  - phantomjs --version
  - casperjs --version

# before_script:

script:
  - npm run travis
  - sleep 1
  - npm run test

after_script:
  - pkill -f jekyll
